### ISSUE TITLE
detected by antivirus on virustotal and windows defender

### ISSUE THREAD

**Issue by Reksy747** [ForzaMods/Forza-Mods-Car-Table#4]
https://www.virustotal.com/gui/file/19b9e9e0ade47da0e81c8357169edad8ec196aff2297b36b423a0ced7ecd3df0/detection

**Comment by szaaamerik** [comment]
yeah so what? I know damn well that it has 20+ detecs. it literally doesnt matter because this is opensource and you can see what it does.
