### ISSUE TITLE
"Waiting for testaddr"

### ISSUE THREAD

**Issue by kranka1** [ForzaMods/Forza-Mods-Car-Table#5]
whenever i try to start the mod it says waiting for testaddr and it wont go away, im on windows11 may that be the issue?

**Comment by Zenly007** [comment]
I'm on 11 too and getting the same issue, dont think its windows or us maybe something on their end they need to update, not sure if forza had any bug patches.

**Comment by szaaamerik** [comment]
the car table is broken, wait for an update

**Comment by 1283376082** [comment]
update lps

**Comment by Raja069** [comment]
> the car table is broken, wait for an update

so, they updated it or not?

**Comment by szaaamerik** [comment]
no

**Comment by szaaamerik** [comment]
Updated.
