### ISSUE TITLE
Not working on Microsoft Horizon 5

### ISSUE THREAD

**Issue by hungryPotato423** [ForzaMods/Forza-Mods-Car-Table#6]
the game keeps selling the FD Viper instead of any car 
it says ID swapped but it's always selling Viper 
It worked perfectly before the update

Were you connected to the internet while trying?  both 

What platform are you on? (Steam or MS)  MS

What system are you running?  Windows 10

Is your game cracked or legitimate?  Legitimate 

How many times did you try before commenting?  a lot

**Comment by szaaamerik** [comment]
closing this issue because  I want a comment on the #3 issue.
